apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-app-deployment
spec: #Defines the Deployment Behaviour
  replices: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: #Defines the Pod Behaviour
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "128MB"
            cpu: "500m"
        ports:
        - containerPort: 3015
